name: flutter_architecture_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #CORE
  equatable: ^2.0.5

  #STATE MANAGEMENT
  flutter_riverpod: ^2.4.5

  #CONFIG
  envied: ^0.3.0+3
  json_annotation: ^4.8.1
  easy_localization: ^3.0.3

  #UTILITY
  kartal: ^3.5.0
  easy_logger: ^0.0.2
  logger: ^2.0.2+1

  #NETWORK
  vexana: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.3.0+3

flutter_Launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sok min:16, default 21
  remove_alpha_ios: true

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - asset/translations/
